version: '3.5'
services:
  xxl-job:
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: fudy-xxl-job
    ports:
      - 8080:8080
    networks:
      - fudy-network 
    volumes:
      - /opt/docker/xxl-job/logs:/data/applogs
    environment:
      - PARAMS=--spring.datasource.username=fudy --spring.datasource.password=123456 --spring.datasource.url=jdbc:mysql://fudy-mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
networks:
  fudy-network:
