version: '3.5'
services:
  elasticsearch:
    image: elasticsearch:8.4.1
    container_name: fudy-elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - fudy-network 
    volumes:
      - /opt/docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /opt/docker/elasticsearch/data:/usr/share/elasticsearch/data
      - /opt/docker/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms64m -Xmx128m
    privileged: true
networks:
  fudy-network:
